#!/usr/bin/env python
"""Fig 3 (combined) - single-cell reanalysis, DIA-NN 1.8.1 vs 2.5.1 Enterprise.

Merges the count overview and the mechanistic multi-view into one figure, with
dataset accessions on every panel. 3 rows x 2 cols (portrait, fills page height):
  A  Per-cell protein groups  (box + jitter, both HeLa datasets x version)
  B  Data-completeness curve  (HeLa Astral) -- the MBR headline
  C  plexDIA deposited vs quantms.io (MSV000093870) -- orthogonal reanalysis axis
  D  Relative rank-abundance  (HeLa Astral) -- depth, normalized to each run's top
  E  CV across cells          (HeLa Astral) -- quantitative precision
  F  legend

Data provenance
---------------
All numbers are derived from the deposited DIA-NN reports by
``analysis/make_single_cell_tables.py`` (run it to (re)generate the inputs):
  * mv_{per_cell,completeness,rank_abundance,cv}.tsv and sc_totals.tsv
    <- PRIDE FTP quantmsdiann-benchmarks/single-cell/{PXD046357,PXD044991}/
       v{1_8_1,2_5_1_enterprise}/quant_tables/diann_report.{tsv,parquet}
       (our reanalysis; counting via analysis/count_report_ids.py, target-only).
  * plexDIA counts (panel F) <- comparison_counts.tsv, generated by
    analysis/plexDIA/figure_msv000093870_galatidou_vs_quantmsdiann.py from the
    quantmsdiann report (PRIDE FTP) vs the published Galatidou 2024 matrix
    (github.com/SlavovLab/single_cell_oocyte).
Pipeline: https://github.com/bigbio/quantmsdiann

Data: data/single_cell/mv_*.tsv, data/single_cell/sc_totals.tsv.

Run:  python -m analysis.figure_single_cell_combined
Out:  analysis/figures/manuscript/fig3_single_cell_combined.svg
"""
from __future__ import annotations

from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import numpy as np
import pandas as pd

from analysis import figure_style as fs
fs.apply_house_style()

REPO = Path(__file__).resolve().parents[1]
D = REPO / "data" / "single_cell"
OUT = REPO / "analysis" / "figures" / "manuscript" / "fig3_single_cell_combined.svg"

VERS = ["1_8_1", "2_5_1_enterprise"]
VLAB = {"1_8_1": "1.8.1", "2_5_1_enterprise": "2.5.1 Enterprise"}
VCOL = {v: fs.VERSION_COLORS[v] for v in VERS}
ACC = {"HeLa Astral SC": "PXD046357", "HeLa One-Tip": "PXD044991"}
FLAG = "HeLa Astral SC"
FLAG_T = f"HeLa Astral SC\n({ACC[FLAG]})"
# plexDIA (Galatidou 2024) protein groups, deposited vs quantms.io reanalysis —
# read from the generated comparison_counts.tsv (no hardcoding).
PLEX_COUNTS = REPO / "analysis" / "figures" / "plexDIA" / "MSV000093870" / "comparison_counts.tsv"


def _load_plex() -> tuple[int, int]:
    df = pd.read_csv(PLEX_COUNTS, sep="\t").set_index("metric")
    row = df.loc["protein_groups_total"]
    return int(row["Galatidou_2024"]), int(row["quantmsdiann"])


DS_STYLE = {"HeLa Astral SC": "-", "HeLa One-Tip": "--"}


def _completeness(ax):
    df = pd.read_csv(D / "mv_completeness.tsv", sep="\t")
    for ds in df["dataset"].unique():
        for v in VERS:
            s = df[(df["dataset"] == ds) & (df["version"] == v)].sort_values("min_cells")
            ax.plot(s["min_cells"], s["n_proteins"], linestyle=DS_STYLE.get(ds, "-"),
                    marker="o", ms=3.5, lw=1.8, color=VCOL[v])
    ax.set_xlabel("quantified in ≥ N cells"); ax.set_ylabel("protein groups")
    ax.set_title("Data completeness")
    fs.kfmt_axis(ax.yaxis); fs.despine(ax)


def _percell(ax):
    df = pd.read_csv(D / "mv_per_cell.tsv", sep="\t")
    datasets = list(dict.fromkeys(df["dataset"]))
    bw = 0.36; rng = np.random.default_rng(0)
    for gi, ds in enumerate(datasets):
        for k, v in enumerate(VERS):
            vals = df[(df["dataset"] == ds) & (df["version"] == v)]["pg_count"].values
            x = gi + (k - 0.5) * bw
            bp = ax.boxplot([vals], positions=[x], widths=bw * 0.85, patch_artist=True, showfliers=False)
            fs.style_boxplot(bp, color=VCOL[v])
            ax.scatter(x + rng.uniform(-0.07, 0.07, len(vals)), vals, s=12, color=VCOL[v], alpha=0.7, edgecolors="none", zorder=3)
    ax.set_xticks(range(len(datasets)))
    ax.set_xticklabels([f"{d}\n({ACC[d]})" for d in datasets])
    ax.set_ylabel("protein groups / cell"); ax.set_title("Per-cell protein groups")
    fs.kfmt_axis(ax.yaxis); fs.despine(ax)


def _plexdia(ax):
    plex_dep, plex_qm = _load_plex()
    vals = [plex_dep, plex_qm]; cols = [fs.COMPARISON["original"], fs.COMPARISON["quantmsdiann"]]
    bw = 0.38; pos = [-bw/2, bw/2]
    b = ax.bar(pos, vals, bw, color=cols, edgecolor="white", linewidth=0.6)
    pct = round(100*(vals[1]-vals[0])/vals[0])
    ax.annotate(f"+{pct}%", (b[1].get_x()+b[1].get_width()/2, vals[1]), textcoords="offset points",
                xytext=(0, 3), ha="center", va="bottom", fontsize=12, fontweight="bold", color=fs.COMPARISON["quantmsdiann"])
    ax.set_xticks(pos); ax.set_xticklabels(["Galatidou 2024\n(deposited)\n1.8.1b16", "quantms.io\n2.5.0"], fontsize=11)
    ax.set_xlim(-0.6, 0.6); ax.set_ylabel("protein groups"); ax.set_title("plexDIA — MSV000093870")
    fs.kfmt_axis(ax.yaxis); fs.despine(ax)


def _rank(ax):
    df = pd.read_csv(D / "mv_rank_abundance.tsv", sep="\t")
    for v in VERS:
        s = df[df["version"] == v].sort_values("rank")
        y = s["log10_intensity"].values - s["log10_intensity"].max()  # relative to top protein
        ax.plot(s["rank"], y, "-", color=VCOL[v], label=VLAB[v])
    ax.set_xlabel("protein group rank"); ax.set_ylabel("log10 intensity (rel. to top)")
    ax.set_title("Dynamic range — HeLa Astral")
    fs.despine(ax)


def _cv(ax):
    df = pd.read_csv(D / "mv_cv.tsv", sep="\t")
    # clip at 1.5 (not 1.0): One-Tip is a low-input prep with a real high-CV
    # tail; clipping at 1.0 piled 12-18% of its proteins into one bin, an
    # artefactual spike. >1.5 is <3% and a small tail mark.
    bins = np.linspace(0, 1.5, 46)
    for ds in df["dataset"].unique():
        for v in VERS:
            cv = df[(df["dataset"] == ds) & (df["version"] == v)]["cv"].clip(0, 1.5)
            ax.hist(cv, bins=bins, density=True, histtype="step", linewidth=1.5,
                    color=VCOL[v], linestyle=DS_STYLE.get(ds, "-"))
    ax.set_xlabel("CV across cells"); ax.set_ylabel("density")
    ax.set_xlim(0, 1.5)
    ax.set_title("Quantitative precision")
    fs.despine(ax)


# Total counts (report-based, target-only): precursors and protein groups,
# 1.8.1 -> 2.5.1 Enterprise, read from the generated sc_totals.tsv (no hardcoding;
# see analysis/make_single_cell_tables.py).
_SHORT = {"HeLa Astral SC": "Astral", "HeLa One-Tip": "One-Tip"}


def _load_totals() -> dict:
    df = pd.read_csv(D / "sc_totals.tsv", sep="\t")
    out: dict = {}
    for ds, g in df.groupby("dataset"):
        gv = g.set_index("version")
        out[_SHORT.get(ds, ds)] = {
            m: (int(gv.loc["1_8_1", m]), int(gv.loc["2_5_1_enterprise", m]))
            for m in ("precursors", "proteins")
        }
    # preserve Astral-then-One-Tip order
    return {k: out[k] for k in ("Astral", "One-Tip") if k in out}


def _totals(ax):
    """Dual-axis totals: precursors (left axis) and protein groups (right axis),
    side by side, so the two very different scales are both readable."""
    bw = 0.36
    ax2 = ax.twinx()
    TOTALS = _load_totals()
    dsx = list(TOTALS)                       # [Astral, One-Tip]
    prec_x = {d: i for i, d in enumerate(dsx)}            # 0, 1
    prot_x = {d: i + len(dsx) + 0.6 for i, d in enumerate(dsx)}  # 2.6, 3.6
    def draw(target, xmap, metric):
        for k, v in enumerate(VERS):
            idx = 0 if v == "1_8_1" else 1
            for d in dsx:
                x = xmap[d] + (k - 0.5) * bw
                hi = TOTALS[d][metric][idx]
                target.bar(x, hi, bw, color=VCOL[v], edgecolor="white", linewidth=0.6)
                if v != "1_8_1":
                    lo = TOTALS[d][metric][0]
                    target.annotate(f"+{round(100*(hi-lo)/lo)}%", (x, hi), textcoords="offset points",
                                    xytext=(0, 3), ha="center", va="bottom", fontsize=10, fontweight="bold", color=VCOL[v])
    draw(ax, prec_x, "precursors")
    draw(ax2, prot_x, "proteins")
    ax.axvline(len(dsx) - 0.2, color="#cccccc", linewidth=0.8)
    ticks = [prec_x[d] for d in dsx] + [prot_x[d] for d in dsx]
    ax.set_xticks(ticks)
    ax.set_xticklabels([d.replace("HeLa ", "").replace(" SC", "") for d in dsx] * 2, fontsize=11)
    ax.set_xlim(-0.7, prot_x[dsx[-1]] + 0.7)
    ax.set_ylabel("precursors"); ax2.set_ylabel("protein groups")
    ax.set_ylim(0, 27000); ax2.set_ylim(0, 5400)
    fs.kfmt_axis(ax.yaxis); fs.kfmt_axis(ax2.yaxis)
    ax.set_title("Total identifications")
    ax.text(np.mean([prec_x[d] for d in dsx]), -0.20, "precursors", transform=ax.get_xaxis_transform(),
            ha="center", va="top", fontsize=11, fontweight="bold")
    ax.text(np.mean([prot_x[d] for d in dsx]), -0.20, "protein groups", transform=ax.get_xaxis_transform(),
            ha="center", va="top", fontsize=11, fontweight="bold")
    for sp in ("top",): ax.spines[sp].set_visible(False); ax2.spines[sp].set_visible(False)


_FULL = {"Astral": "HeLa Astral SC", "One-Tip": "HeLa One-Tip"}


def _merged(ax):
    """Merged A+B panel: three x-sections sharing the figure, 1.8.1 vs 2.5.1
    Enterprise. (i) total precursors (left axis), (ii) total protein groups and
    (iii) per-cell protein groups (box+jitter) both on the right axis (same
    scale). Replaces the separate totals + per-cell panels."""
    bw = 0.36
    ax2 = ax.twinx()
    TOTALS = _load_totals()
    dsx = list(TOTALS)                                   # [Astral, One-Tip]
    percell = pd.read_csv(D / "mv_per_cell.tsv", sep="\t")
    prec_x = {d: i for i, d in enumerate(dsx)}                       # 0, 1
    prot_x = {d: i + len(dsx) + 0.6 for i, d in enumerate(dsx)}      # 2.6, 3.6
    cell_x = {d: i + 2 * len(dsx) + 1.2 for i, d in enumerate(dsx)}  # 5.2, 6.2
    rng = np.random.default_rng(0)
    for k, v in enumerate(VERS):
        idx = 0 if v == "1_8_1" else 1
        for d in dsx:
            # (i) precursors total — left axis
            xp = prec_x[d] + (k - 0.5) * bw
            hp = TOTALS[d]["precursors"][idx]
            ax.bar(xp, hp, bw, color=VCOL[v], edgecolor="white", linewidth=0.6)
            if v != "1_8_1":
                lo = TOTALS[d]["precursors"][0]
                ax.annotate(f"+{round(100*(hp-lo)/lo)}%", (xp, hp), textcoords="offset points",
                            xytext=(0, 3), ha="center", va="bottom", fontsize=9, fontweight="bold", color=VCOL[v])
            # (ii) protein groups total — right axis
            xt = prot_x[d] + (k - 0.5) * bw
            hg = TOTALS[d]["proteins"][idx]
            ax2.bar(xt, hg, bw, color=VCOL[v], edgecolor="white", linewidth=0.6)
            if v != "1_8_1":
                lo = TOTALS[d]["proteins"][0]
                ax2.annotate(f"+{round(100*(hg-lo)/lo)}%", (xt, hg), textcoords="offset points",
                             xytext=(0, 3), ha="center", va="bottom", fontsize=9, fontweight="bold", color=VCOL[v])
            # (iii) per-cell protein groups — right axis (box + jitter)
            xc = cell_x[d] + (k - 0.5) * bw
            vals = percell[(percell["dataset"] == _FULL[d]) & (percell["version"] == v)]["pg_count"].values
            bp = ax2.boxplot([vals], positions=[xc], widths=bw * 0.85, patch_artist=True, showfliers=False)
            fs.style_boxplot(bp, color=VCOL[v])
            ax2.scatter(xc + rng.uniform(-0.07, 0.07, len(vals)), vals, s=9, color=VCOL[v],
                        alpha=0.6, edgecolors="none", zorder=3)
    ax.axvline(len(dsx) - 0.2, color="#cccccc", linewidth=0.8)
    ax.axvline(prot_x[dsx[-1]] + 0.7, color="#cccccc", linewidth=0.8)
    ticks = [prec_x[d] for d in dsx] + [prot_x[d] for d in dsx] + [cell_x[d] for d in dsx]
    ax.set_xticks(ticks)
    ax.set_xticklabels([d.replace("HeLa ", "").replace(" SC", "") for d in dsx] * 3, fontsize=10)
    ax.set_xlim(-0.7, cell_x[dsx[-1]] + 0.7)
    ax.set_ylabel("precursors"); ax2.set_ylabel("protein groups")
    ax.set_ylim(0, 27000); ax2.set_ylim(0, 5400)
    fs.kfmt_axis(ax.yaxis); fs.kfmt_axis(ax2.yaxis)
    ax.set_title("Total identifications and per-cell protein groups")
    for xs, lab in ((prec_x, "precursors\n(total)"), (prot_x, "protein groups\n(total)"),
                    (cell_x, "protein groups\n(per cell)")):
        ax.text(np.mean([xs[d] for d in dsx]), -0.16, lab, transform=ax.get_xaxis_transform(),
                ha="center", va="top", fontsize=10, fontweight="bold")
    for sp in ("top",):
        ax.spines[sp].set_visible(False); ax2.spines[sp].set_visible(False)


def render(out: Path) -> Path:
    # plexDIA (old F) moved to the reanalysis figure; dynamic range (old D)
    # dropped. Layout: merged totals+per-cell spanning the top, then the two
    # mechanistic panels (completeness, CV) below.
    fig = plt.figure(figsize=(10.5, 9.0))
    gs = fig.add_gridspec(2, 2, height_ratios=[1.05, 1.0], hspace=0.42, wspace=0.28)
    ax_merged = fig.add_subplot(gs[0, :])
    ax_comp = fig.add_subplot(gs[1, 0])
    ax_cv = fig.add_subplot(gs[1, 1])
    _merged(ax_merged); _completeness(ax_comp); _cv(ax_cv)
    handles = [Line2D([0], [0], color=VCOL[v], marker="o", linewidth=2, markersize=8,
               label=f"DIA-NN {VLAB[v]}") for v in VERS]
    handles += [Line2D([0], [0], color="#555555", linestyle="-", linewidth=2, label="HeLa Astral (PXD046357)"),
                Line2D([0], [0], color="#555555", linestyle="--", linewidth=2, label="HeLa One-Tip (PXD044991)")]
    fig.legend(handles=handles, loc="upper center", ncol=4, bbox_to_anchor=(0.5, 1.01), fontsize=11)
    for a, lab in zip([ax_merged, ax_comp, ax_cv], "ABC"):
        a.text(-0.06, 1.05, lab, transform=a.transAxes, fontsize=17, fontweight="bold", va="bottom", ha="right")
    fig.tight_layout(rect=(0, 0, 1, 0.95), h_pad=2.6, w_pad=2.2)
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out); plt.close(fig)
    return out


def main() -> int:
    print(f"wrote {render(OUT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
